<a href="https://colab.research.google.com/github/Pranayshukla0610/basic-python/blob/main/02_Excel_API_Data_Ingestion_and_Dataset_Understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import json
import requests
import os
from pathlib import Path

from sqlalchemy import create_engine

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv')
df.to_excel(
    '/content/ecommerce_sales_34500-selected-columns.xlsx',
    index=False
)

In [ ]:
excel_df = pd.read_excel('/content/ecommerce_sales_34500-selected-columns.xlsx')
excel_df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
excel_df = pd.read_excel(
    "/content/ecommerce_sales_34500-selected-columns.xlsx",
    sheet_name=0
)

In [ ]:
with pd.ExcelWriter(
    "sales_multiple_sheets.xlsx",
    engine="openpyxl"
) as writer:

    df.head(100).to_excel(
        writer,
        sheet_name="Sample",
        index=False
    )

    df.tail(100).to_excel(
        writer,
        sheet_name="Last_100",
        index=False
    )

In [ ]:
all_sheets = pd.read_excel(
    "sales_multiple_sheets.xlsx",
    sheet_name=None
)

In [ ]:
all_sheets.keys()

dict_keys(['Sample', 'Last_100'])

In [ ]:
sample_df = all_sheets['Sample']

In [ ]:
df.to_json(
    'sales.json',
    orient='records',
    indent=4
)

In [ ]:
json_df = pd.read_json(
    'sales.json'
)

In [ ]:
json_df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
json_df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
with open(
    "sales.json",
    "r",
    encoding="utf-8"
) as file:

  data = json.load(file)

In [ ]:
type(data)

list

In [ ]:
json_df = pd.DataFrame(data)

In [ ]:
nested_data = {
    "customers": [
        {
            "customer_id": 1,
            "name": "John",
            "address": {
                "city": "Delhi",
                "country": "India"
            }
        },
        {
            "customer_id": 2,
            "name": "Rahul",
            "address": {
                "city": "Mumbai",
                "country": "India"
            }
        }
    ]
}

API INGESTION

In [ ]:
url = "https://jsonplaceholder.typicode.com/users"

In [ ]:
response = requests.get(
    url
)

In [ ]:
print(
    response.status_code
)

200

In [ ]:
data = response.json()

In [ ]:
type(json)

module

In [ ]:
api_df = pd.DataFrame(
    data
)

In [ ]:
api_df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [ ]:
url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(
    url,
    timeout=10
)

response.raise_for_status()

data = response.json()

api_df = pd.DataFrame(
    data
)

api_df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

API Error Handling

In [ ]:
try:

    response = requests.get(
        url,
        timeout=10
    )

    response.raise_for_status()

    data = response.json()

    api_df = pd.DataFrame(data)

    print(
        "Data successfully ingested"
    )

except requests.exceptions.RequestException as e:

    print(
        "API request failed:",
        e
    )

Data successfully ingested

API Parameters

In [ ]:
params = {
    "page": 1,
    "limit": 100
}

In [ ]:
response = requests.get(
    url,
    params=params,
    timeout=10
)

API Headers

In [ ]:
headers = {
    "Authorization": "Bearer YOUR_API_KEY",
    "Accept": "application/json"
}

In [ ]:
response = requests.get(
    url,
    headers=headers,
    timeout=10
)

API Pagination

In [ ]:
all_records = []

for page in range(1, 6):

    params = {
        "page": page,
        "limit": 100
    }

    response = requests.get(
        url,
        params=params,
        timeout=10
    )

    response.raise_for_status()

    data = response.json()

    all_records.extend(data)

In [ ]:
api_df = pd.DataFrame(
    all_records
)