<a href="https://colab.research.google.com/github/Pranayshukla0610/basic-python/blob/main/03_SQL_PARQUET_Data_Ingestion_and_Dataset_Understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import json
import requests
import os
import numpy as np

In [2]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv')
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [6]:
df.to_json(
    '/content/ecommerce_sales_34500-selected-columns.csv',
    orient = 'records',
    indent=4
)

In [7]:
json_df = pd.read_json('/content/ecommerce_sales_34500-selected-columns.csv')
json_df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [8]:
type(json_df)

pandas.core.frame.DataFrame

In [9]:
with open(
    "/content/ecommerce_sales_34500-selected-columns.csv",
    "r",
    encoding="utf-8"
) as file:
    data = json.load(file)

In [10]:
type(data)

list

In [11]:
json_df = pd.DataFrame(data)

In [13]:
nested_data={
    "customers":[
        {
            "customer_id":1,
            "name":"John",
            "address":{
                "city":"New Delhi",
                "country":"India"
            }
        },
        {
            "customer_id":2,
            "name":"Rahul",
            "address":{
                "city":"Mumbai",
                "country":"India"
            }
        }
    ]
}

In [14]:
from pandas import json_normalize

nested_df = json_normalize(
    nested_data['customers']
)

In [15]:
nested_df

   customer_id   name address.city address.country
0            1   John    New Delhi           India
1            2  Rahul       Mumbai           India

API INGESTION

In [16]:
url = "https://jsonplaceholder.typicode.com/users"

In [17]:
response = requests.get(
    url
)

In [18]:
print(
    response.status_code
)

200

In [19]:
data = response.json()

In [20]:
type(data)

list

In [21]:
api_df = pd.DataFrame(
    data
)

In [22]:
api_df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [23]:
url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(
    url,
    timeout=10
)

response.raise_for_status()

data = response.json()

api_df = pd.DataFrame(
    data
)

api_df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [24]:
try:
  response=requests.get(
      url,
      timeout=10
  )

  response.raise_for_status()

  data = response.json()

  api_df = pd.DataFrame(
      data
  )

  print("Data Successfully Ingested")

except request.exceptions.RequestException as e:

  print(
      "API Request Failed",
      e
  )

Data Successfully Ingested

API Parameters

In [25]:
params = {
    "page":1,
    "limit":100
}

In [26]:
response = requests.get(
    url,
    params=params,
    timeout=10
)

In [27]:
headers = {
    "Authorization":"Bearer https://jsonplaceholder.typicode.com/users",
    "Accept":"application/json"
}

In [29]:
response = requests.get(
    url,
    headers=headers,
    timeout=10
)

In [30]:
all_records=[]

for page in range(1,6):

  params = {
      "page":page,
      "limit":100
  }

  response = requests.get(
      url,
      params=params,
      timeout=10
  )

  response.raise_for_status()

  data = response.json()

  all_records.extend(data)

In [31]:
api_df = pd.DataFrame(all_records)

In [32]:
api_df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

#SQL DATABASE INGESTION

In [33]:
from sqlalchemy import create_engine

engine = create_engine(
    'sqlite:///sales.db'
)

In [34]:
df.to_sql(
    '/content/ecommerce_sales_34500-selected-columns.csv',
    engine,
    if_exists='replace',
    index=False
)

34500

In [36]:
query = """
  SELECT name,
         email,
         address,
         phone,
         website
  FROM sales"""

In [38]:
customers = pd.DataFrame({
    "Customer ID":[1,2,3],
    "Customer Name":[
        "Rahul",
        "Amit",
        "Priya"
    ]
})

In [39]:
customers.to_sql(
    "customers",
    engine,
    if_exists="replace",
    index=False
)

3

In [40]:
query = """
  SELECT
    s.*,
    c."Customer Name"
  FROM sales s
  JOIN customers c
    ON s."Customer ID" = c."Customer ID"
"""

SQL CHUNK PROCESSING

In [41]:
query = """
  SELECT *
  FROM sales
"""

#PARQUET

In [50]:
import pandas as pd

df = pd.read_json('/content/ecommerce_sales_34500-selected-columns.csv')

df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [51]:
df.to_parquet(
    "/content/ecommerce_sales_34500-selected-columns.parquet",
    index=False
)

In [56]:
parquet_df = pd.read_parquet(
    "/content/ecommerce_sales_34500-selected-columns.parquet",
    columns=[
        "product_id",
        "quantity"
    ]
)

parquet_df.head()

  product_id  quantity
0    P234890         1
1    P228204         1
2    P213892         1
3    P208689         1
4    P228063         1

In [59]:
csv_size = os.path.getsize(
    "/content/ecommerce_sales_34500-selected-columns.csv"
)

parquet_size = os.path.getsize(
    "/content/ecommerce_sales_34500-selected-columns.parquet"
)

print(
    "CSV:",
    csv_size / (1024 * 1024),
    "MB"
)

print(
    "Parquet:",
    parquet_size / (1024 * 1024),
    "MB"
)

CSV: 10.166335105895996 MB
Parquet: 0.749267578125 MB