<a href="https://colab.research.google.com/github/Pranayshukla0610/basic-python/blob/main/Python_Pandas_Library_Practice_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Find Employees Whose Salary is More Than 20% Above Department Average

import pandas as pd

df = pd.DataFrame({
    "Employee":["A","B","C","D","E","F"],
    "Department":["HR","HR","IT","IT","Sales","Sales"],
    "Salary":[50000,70000,80000,90000,45000,60000]
})

In [2]:
df["dept_avg"] = df.groupby('Department')['Salary'].transform("mean")
result = df[df['Salary'] > 0.2 *df['dept_avg']]
print(result)

  Employee Department  Salary  dept_avg
0        A         HR   50000   60000.0
1        B         HR   70000   60000.0
2        C         IT   80000   85000.0
3        D         IT   90000   85000.0
4        E      Sales   45000   52500.0
5        F      Sales   60000   52500.0

In [4]:
#Find First Employee Hired in Every Department

import pandas as pd

df = pd.DataFrame({
    "Employee":["A","B","C","D","E","F"],
    "Department":["HR","HR","IT","IT","Sales","Sales"],
    "Joining_Date":[
        "2022-03-01",
        "2021-05-10",
        "2020-01-15",
        "2023-04-20",
        "2019-07-01",
        "2022-08-15"
    ]
})

df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
df

  Employee Department Joining_Date
0        A         HR   2022-03-01
1        B         HR   2021-05-10
2        C         IT   2020-01-15
3        D         IT   2023-04-20
4        E      Sales   2019-07-01
5        F      Sales   2022-08-15

In [5]:
idx = df.groupby('Department')['Joining_Date'].idxmin()

print(df.loc[idx])

  Employee Department Joining_Date
1        B         HR   2021-05-10
2        C         IT   2020-01-15
4        E      Sales   2019-07-01

In [7]:
#Calculate Running Total of Salary Inside Each Department

import pandas as pd

df = pd.DataFrame({
    "Department":["HR","HR","HR","IT","IT","Sales"],
    "Employee":["A","B","C","D","E","F"],
    "Salary":[40000,50000,60000,70000,80000,90000]
})
df

  Department Employee  Salary
0         HR        A   40000
1         HR        B   50000
2         HR        C   60000
3         IT        D   70000
4         IT        E   80000
5      Sales        F   90000

In [10]:
df['running_tot'] = df.groupby('Department')['Salary'].cumsum()
print(df)

  Department Employee  Salary  running_tot
0         HR        A   40000        40000
1         HR        B   50000        90000
2         HR        C   60000       150000
3         IT        D   70000        70000
4         IT        E   80000       150000
5      Sales        F   90000        90000

In [11]:
#Find Employee Number Inside Each Department

import pandas as pd

df = pd.DataFrame({
    "Department":["HR","HR","HR","IT","IT","Sales"],
    "Employee":["A","B","C","D","E","F"]
})

In [13]:
df['emp_num'] = df.groupby('Department')['Employee'].cumcount()+1
print(df)

  Department Employee  emp_num
0         HR        A        1
1         HR        B        2
2         HR        C        3
3         IT        D        1
4         IT        E        2
5      Sales        F        1

In [14]:
#Number Every Department

import pandas as pd

df = pd.DataFrame({
    "Department":["HR","HR","IT","IT","Sales","Finance"]
})

In [16]:
df["Dept_Id"] = df.groupby('Department').ngroup()
print(df)

  Department  Dept_Id
0         HR        1
1         HR        1
2         IT        2
3         IT        2
4      Sales        3
5    Finance        0

In [19]:
#Replace Department Names Using Mapping

import pandas as pd

df = pd.DataFrame({
    "Department":["HR","IT","Sales","Finance"]
})
df

  Department
0         HR
1         IT
2      Sales
3    Finance

In [18]:
mapping = {
    "HR":"Human Resources",
    "IT":"Information Technology",
    "Sales":"Sales Team",
    "Finance":"Finance Team"
}

df['Department'] = df['Department'].map(mapping)
print(df)

               Department
0         Human Resources
1  Information Technology
2              Sales Team
3            Finance Team

In [20]:
#Find Department Having Maximum Employees

import pandas as pd

df = pd.DataFrame({
    "Department":[
        "HR","HR","HR",
        "IT","IT",
        "Sales","Sales","Sales","Sales"
    ]
})

In [23]:
count = df["Department"].value_counts()

print(count)

print("Department:", count.idxmax())

Department
Sales    4
HR       3
IT       2
Name: count, dtype: int64
Department: Sales

In [24]:
#Find Departments Having At Least Three Employees

import pandas as pd

df = pd.DataFrame({
    "Department":[
        "HR","HR","HR",
        "IT","IT",
        "Sales","Sales","Sales",
        "Finance"
    ]
})

In [25]:
results = df.groupby('Department').filter(lambda x: len(x) >= 3)
print(results)

  Department
0         HR
1         HR
2         HR
5      Sales
6      Sales
7      Sales

In [26]:
#Merge Employee and Department Tables

import pandas as pd

employees = pd.DataFrame({
    "EmpID":[101,102,103],
    "DepartmentID":[1,2,1]
})

departments = pd.DataFrame({
    "DepartmentID":[1,2],
    "Department":["HR","IT"]
})

In [27]:
result = employees.merge(
    departments,
    on='DepartmentID',
    how='inner'
)
print(result)

   EmpID  DepartmentID Department
0    101             1         HR
1    102             2         IT
2    103             1         HR